In [1]:
from tqdm import tqdm
import pandas as pd
import re

In [2]:
df_sent_comp=pd.read_excel('../output/qsw_subtract.xlsx')

### Male kinship extraction.

In [3]:
re_rule_list=[r'(遠祖|其先|三十一世祖|十八世祖|十六代祖|十五代祖|十三代祖|十二世祖|十二代祖|六代祖|十代祖|十一代祖|十一世祖|十世祖|九世祖|八世祖|七世祖|六世祖|五世祖|五代祖|高祖|四世祖|四代祖|高祖母|四代祖母|曾祖|曾祖考|曾大父|大王父|曾王父|曾祖王父|皇曾祖|曾大考|曾伯祖|曾叔祖|先祖|先祖考|先大父|先王父|大父|王父|皇祖考|大考|祖|從祖|族祖|伯祖|伯祖父|叔祖父|叔祖|從伯祖|父|考|皇考|先父|先考|先君|伯父|世父|叔父|族父|再從伯|再從叔|再從舅|從伯|從父|從伯父|從叔|從叔父|從舅|外舅|母舅|外曾大父|外曾王父|外曾祖父|外祖|外祖父|外王父|外大父|外叔祖|外伯祖|舅|從舅|再從舅|外舅|舅|外伯父|外叔父|外大祖|外曾祖)[諱|曰](.{0,2}?)/',
              r'^(遠祖|三十一世祖|十八世祖|十六代祖|十五代祖|十三代祖|十二世祖|十二代祖|六代祖|十代祖|十一代祖|十一世祖|十世祖|九世祖|八世祖|七世祖|六世祖|五世祖|五代祖|高祖|四世祖|四代祖|高祖母|四代祖母|曾祖|曾祖考|曾大父|大王父|曾王父|曾祖王父|皇曾祖|曾大考|曾伯祖|曾叔祖|先祖|先祖考|先大父|先王父|大父|王父|皇祖考|大考|祖|從祖|族祖|伯祖|伯祖父|叔祖父|叔祖|從伯祖|父|考|皇考|先父|先考|伯父|世父|叔父|族父|再從伯|再從叔|再從舅|從伯|從父|從伯父|從叔|從叔父|從舅|外舅|母舅|外曾大父|外曾王父|外曾祖父|外祖|外祖父|外王父|外大父|外叔祖|外伯祖|舅|從舅|再從舅|外舅|舅|外伯父|外叔父|外大祖|外曾祖)([^居某早丧卒母妣諱曰也]{0,2})/',
              r'[公君吾夫人我/](遠祖|三十一世祖|十八世祖|十六代祖|十五代祖|十三代祖|十二世祖|十二代祖|六代祖|十代祖|十一代祖|十一世祖|十世祖|九世祖|八世祖|七世祖|六世祖|五世祖|五代祖|高祖|四世祖|四代祖|高祖母|四代祖母|曾祖|曾祖考|曾大父|大王父|曾王父|曾祖王父|皇曾祖|曾大考|曾伯祖|曾叔祖|先祖|先祖考|先大父|先王父|大父|王父|皇祖考|大考|祖|從祖|族祖|伯祖|伯祖父|叔祖父|叔祖|從伯祖|父|考|皇考|先父|先考|伯父|世父|叔父|族父|再從伯|再從叔|再從舅|從伯|從父|從伯父|從叔|從叔父|從舅|外舅|母舅|外曾大父|外曾王父|外曾祖父|外祖|外祖父|外王父|外大父|外叔祖|外伯祖|舅|從舅|再從舅|外舅|舅|外伯父|外叔父|外大祖|外曾祖)([^居某早丧卒母妣諱曰也]{0,2}?)/',
              r'[公君吾夫人我/](遠祖|三十一世祖|十八世祖|十六代祖|十五代祖|十三代祖|十二世祖|十二代祖|六代祖|十代祖|十一代祖|十一世祖|十世祖|九世祖|八世祖|七世祖|六世祖|五世祖|五代祖|高祖|四世祖|四代祖|高祖母|四代祖母|曾祖|曾祖考|曾大父|大王父|曾王父|曾祖王父|皇曾祖|曾大考|曾伯祖|曾叔祖|先祖|先祖考|先大父|先王父|大父|王父|皇祖考|大考|祖|從祖|族祖|伯祖|伯祖父|叔祖父|叔祖|從伯祖|父|考|皇考|先父|先考|伯父|世父|叔父|族父|再從伯|再從叔|再從舅|從伯|從父|從伯父|從叔|從叔父|從舅|外舅|母舅|外曾大父|外曾王父|外曾祖父|外祖|外祖父|外王父|外大父|外叔祖|外伯祖|舅|從舅|再從舅|外舅|舅|外伯父|外叔父|外大祖|外曾祖)([^居某早丧卒母妣諱曰也]{0,2}?)$',
              r'(遠祖|其先|三十一世祖|十八世祖|十六代祖|十五代祖|十三代祖|十二世祖|十二代祖|六代祖|十代祖|十一代祖|十一世祖|十世祖|九世祖|八世祖|七世祖|六世祖|五世祖|五代祖|高祖|四世祖|四代祖|高祖母|四代祖母|曾祖|曾祖考|曾大父|大王父|曾王父|曾祖王父|皇曾祖|曾大考|曾伯祖|曾叔祖|先祖|先祖考|先大父|先王父|大父|王父|皇祖考|大考|祖|從祖|族祖|伯祖|伯祖父|叔祖父|叔祖|從伯祖|父|考|皇考|先父|先考|先君|伯父|世父|叔父|族父|再從伯|再從叔|再從舅|從伯|從父|從伯父|從叔|從叔父|從舅|外舅|母舅|外曾大父|外曾王父|外曾祖父|外祖|外祖父|外王父|外大父|外叔祖|外伯祖|舅|從舅|再從舅|外舅|舅|外伯父|外叔父|外大祖|外曾祖)(某官{0,1}?)',
              r'(遠祖|其先|三十一世祖|十八世祖|十六代祖|十五代祖|十三代祖|十二世祖|十二代祖|六代祖|十代祖|十一代祖|十一世祖|十世祖|九世祖|八世祖|七世祖|六世祖|五世祖|五代祖|高祖|四世祖|四代祖|高祖母|四代祖母|曾祖|曾祖考|曾大父|大王父|曾王父|曾祖王父|皇曾祖|曾大考|曾伯祖|曾叔祖|先祖|先祖考|先大父|先王父|大父|王父|皇祖考|大考|祖|從祖|族祖|伯祖|伯祖父|叔祖父|叔祖|從伯祖|父|考|皇考|先父|先考|先君|伯父|世父|叔父|族父|再從伯|再從叔|再從舅|從伯|從父|從伯父|從叔|從叔父|從舅|外舅|母舅|外曾大父|外曾王父|外曾祖父|外祖|外祖父|外王父|外大父|外叔祖|外伯祖|舅|從舅|再從舅|外舅|舅|外伯父|外叔父|外大祖|外曾祖)[諱|曰](.{0,2})$',
             ]

In [4]:
df_sent_comp.sample(3)

,content_id,subject,author,sent,sent_comp,nz,ns,no_noc,vno
16234,8715557,NaN,王象祖,陳君卿墓誌銘（題）天台王象祖撰有宋嘉泰元年/wsep/臺之舉進士者踰七千,陳君卿墓誌銘（題）/ns/王象祖撰有宋嘉泰元年/wsep/臺之/vno//no_noc/者踰七千,NaN,天台,進士,舉
29851,5764714,林頤叔,葉適,正仲名頤叔/wsep/寬整有局量/wsep/朋友愛信,正仲名頤叔/wsep/寬整有局量/wsep/朋友愛信,NaN,NaN,NaN,NaN
38360,5631368,劉令猷,周必大,會太夫人卒/wsep/君病遂劇/wsep/以十一月十八日亦卒/wsep/享年四十四/wsep...,會太夫人卒/wsep/君病遂劇/wsep/以十一月十八日亦卒/wsep/享年四十四/wsep...,NaN,連山#廬陵,NaN,NaN

In [5]:
kin_list=[]
df_kin_extracted=pd.DataFrame()
for re_rule in re_rule_list:
    for index in tqdm(df_sent_comp.index):
        string=df_sent_comp.loc[index, 'sent_comp']
        content_id=df_sent_comp.loc[index, 'content_id']
        author=df_sent_comp.loc[index, 'author']
        subj=df_sent_comp.loc[index, 'subject']
        kin_list_temp=re.findall(re_rule, string)
        if kin_list_temp!=[]:
            df_kin_extracted=pd.concat([pd.DataFrame([[index, content_id, author, subj, kin[0], kin[1]] for kin in kin_list_temp]), df_kin_extracted], ignore_index=True)

100%|██████████| 57733/57733 [00:09<00:00, 5986.59it/s]
100%|██████████| 57733/57733 [00:14<00:00, 4095.88it/s]
100%|██████████| 57733/57733 [00:09<00:00, 5805.62it/s]
100%|██████████| 57733/57733 [00:06<00:00, 8830.91it/s]
100%|██████████| 57733/57733 [00:07<00:00, 8121.50it/s]
100%|██████████| 57733/57733 [00:05<00:00, 9646.89it/s]

In [6]:
df_kin_extracted.columns=['sent_comp_index', 'content_id', 'author', 'subject', 'kin', 'name']
df_kin_extracted.sample(3)

      sent_comp_index  content_id author   subject kin name
1504            51227     5310033     楊時        張序   祖   延祚
5223            22562     5888939    劉克莊  林瑑女、劉克莊妻   父    瑑
1444            53376     5261351    黄庭堅       王純中   父    固

In [7]:
for index in tqdm(df_kin_extracted.index):
    sent_comp_index = df_kin_extracted.loc[index, 'sent_comp_index']
    df_temp=df_sent_comp.loc[sent_comp_index][['sent', 'sent_comp', 'nz','ns','no_noc','vno']]
    df_kin_extracted.loc[index, 'sent']=df_temp['sent']
    df_kin_extracted.loc[index, 'sent_comp']=df_temp['sent_comp']
    df_kin_extracted.loc[index, 'nz']=df_temp['nz']
    df_kin_extracted.loc[index, 'ns']=df_temp['ns']
    df_kin_extracted.loc[index, 'no_noc']=df_temp['no_noc']
    df_kin_extracted.loc[index, 'vno']=df_temp['vno']

In [8]:
df_kin_extracted.sample(3)

,sent_comp_index,content_id,author,subject,kin,name,sent,sent_comp,nz,ns,no_noc,vno
2925,70128,4982318,王禹偁,NaN,父,進遠,父進遠/wsep/宣州節度副使/wsep/贈右監門衛率府率,父進遠/wsep//ns//no_noc//wsep/贈右監/no_noc//no_noc/,NaN,宣州,節度副使#率府率#門衛,NaN
5257,21700,5889307,劉克莊,鄭宗超,大父,偉,大父偉/wsep/嚴州通守,大父偉/wsep//ns/通守,NaN,嚴州,NaN,NaN
3901,48091,5338842,慕容彦逢,王世彦女,父,世彦,父世彦/wsep/朝散郎,父世彦/wsep//no_noc/,NaN,NaN,朝散郎,NaN

In [9]:
df_kin_extracted[df_kin_extracted['name']!=''].sample(5)

,sent_comp_index,content_id,author,subject,kin,name,sent,sent_comp,nz,ns,no_noc,vno
3120,65861,5072239,范鎮,宋敏求,父,綬,父綬/wsep/兵部尚書/wsep/參知政事/wsep/贈太師/wsep/中書令/wsep/...,父綬/wsep//no_noc//wsep//no_noc//wsep//vno//no_n...,NaN,燕國,參知政事#兵部尚書#尚書令#中書令#太師,贈
8160,14768,5062215,歐陽修,程琳,祖,贊明,祖諱贊明/wsep/贈太師/wsep/中書令,祖諱贊明/wsep//vno//no_noc//wsep//no_noc/,NaN,NaN,中書令#太師,贈
2187,28645,5775381,孫應時,宋天則,祖,彦邦,世家遂安/wsep/曾祖奕/wsep/祖彦邦/wsep/父時中/wsep/好義長者/wsep...,世家/ns//wsep/曾祖奕/wsep/祖彦邦/wsep/父時中/wsep/好義長者/ws...,NaN,遂安,大夫,NaN
2820,2366,5866137,方大琮,NaN,伯父,賴之,娶顧氏/wsep/同邑審計院澣之長女/wsep/尤儉勤/wsep/事姑鄭安人孝謹/wsep/...,娶顧氏/wsep//ns//no_noc/澣之長女/wsep/尤儉勤/wsep/事姑鄭/no...,NaN,同邑,審計院#安人,NaN
1153,68489,5042241,余靖,魏清,考,讜,曾祖玭/wsep/祖爽/wsep/考讜/wsep/并以唐祚衰季/wsep/帥臣專兵/wsep...,曾祖玭/wsep/祖爽/wsep/考讜/wsep/并以唐祚衰季/wsep//no_noc/專...,NaN,雄州,帥臣,NaN

In [10]:
df_kin_extracted[df_kin_extracted['name']!=''].drop('sent_comp_index', axis=1).sort_values(by='content_id').to_excel('../output/df_qsw_kin_extracted_male.xlsx', encoding='utf8')

### Female kinship extraction.

In [11]:
re_rule_list=[r'(曾祖母|曾祖妣|曾大母|曾王母|曾祖姑|祖母|王母|大王母|大母|祖妣|從祖母|外叔祖母|繼祖母|叔祖母|祖姑|從祖姑|伯祖母|叔祖母|伯母|叔母|姑|仲姑|從姑|母|妣|皇妣|先妣|後母|繼母|嫡母|生母|庶母|再從姑|從伯姑|族母|姨母|姨|外姑|外王母|外祖母|外伯祖母|從妗|外姑|姨|姑)([^曰也].{0,20}?)氏',
              r'(娶|取|配)(.{1,10}?)氏',
              r'(繼)([^母].{0,10}?)氏',
             ]

In [12]:
kin_list=[]
df_kin_extracted=pd.DataFrame()
for re_rule in re_rule_list:
    for index in tqdm(df_sent_comp.index):
        string=df_sent_comp.loc[index, 'sent_comp']
        content_id=df_sent_comp.loc[index, 'content_id']
        author=df_sent_comp.loc[index, 'author']
        subj=df_sent_comp.loc[index, 'subject']
        kin_list_temp=re.findall(re_rule, string)
        if kin_list_temp!=[]:
            for kin_nm in kin_list_temp:
                if kin_nm[1]!='':
                    kin_nm=(kin_nm[0], kin_nm[1][-1])
                df_kin_extracted=pd.concat([pd.DataFrame([[index, content_id, author, subj, kin_nm[0], kin_nm[1]]]), df_kin_extracted], ignore_index=True)
#                 else:
#                     print(string, kin_list_temp)

100%|██████████| 57733/57733 [00:11<00:00, 5037.65it/s]
100%|██████████| 57733/57733 [00:12<00:00, 4458.30it/s]
100%|██████████| 57733/57733 [00:06<00:00, 9159.67it/s]

In [13]:
df_kin_extracted.columns=['sent_comp_index', 'content_id', 'author', 'subject', 'kin', 'name']
df_kin_extracted.sample(3)

      sent_comp_index  content_id author subject  kin name
2901             5443     5764371     葉適     NaN    娶    劉
4142            38850     5600680     陸游     周必正  曾祖妣    郭
1074            50924     5310143     楊時     周武仲    娶    楊

In [14]:
for index in tqdm(df_kin_extracted.index):
    sent_comp_index = df_kin_extracted.loc[index, 'sent_comp_index']
    df_temp=df_sent_comp.loc[sent_comp_index][['sent', 'sent_comp', 'nz','ns','no_noc','vno']]
    df_kin_extracted.loc[index, 'sent']=df_temp['sent']
    df_kin_extracted.loc[index, 'sent_comp']=df_temp['sent_comp']
    df_kin_extracted.loc[index, 'nz']=df_temp['nz']
    df_kin_extracted.loc[index, 'ns']=df_temp['ns']
    df_kin_extracted.loc[index, 'no_noc']=df_temp['no_noc']
    df_kin_extracted.loc[index, 'vno']=df_temp['vno']

100%|██████████| 5623/5623 [00:41<00:00, 134.25it/s]

In [15]:
df_kin_extracted.sample(3)

,sent_comp_index,content_id,author,subject,kin,name,sent,sent_comp,nz,ns,no_noc,vno
671,61535,5140864,王安石,蘇安世,娶,郭,君娶南陽郭氏/wsep/又娶清河張氏/wsep/爲清河縣君,君娶/ns/郭氏/wsep/又娶/ns/張氏/wsep//vno//ns//no_noc/,NaN,南陽#清河#清河,縣君,爲
3917,46070,5387994,劉一止,張旬,母,丁,母丁氏/wsep/追封碩人,母丁氏/wsep//vno//no_noc/,NaN,NaN,碩人,追封
5542,1895,8715392,陳鑒,陳元吉,妣,王,妣王氏/wsep/贈安人/wsep/生二男/wsep/先君序爲長,妣王氏/wsep//vno//no_noc//wsep/生二男/wsep/先君序爲長,NaN,NaN,安人,贈

In [16]:
df_kin_extracted[df_kin_extracted['name']!=''].sample(5)

,sent_comp_index,content_id,author,subject,kin,name,sent,sent_comp,nz,ns,no_noc,vno
4202,37819,5631939,周必大,歐陽鈇,母,何,伯威侍母何氏/wsep/攜諸幼/wsep/護柩千里/wsep/返葬永和鎮/wsep/畢二弟三...,伯威侍母何氏/wsep/攜諸幼/wsep/護柩千里/wsep/返葬/ns/鎮/wsep/畢二...,NaN,永和,NaN,NaN
4842,17286,8712687,富紹榮,范柔,祖母,王,祖子開/wsep/贈中散大夫/wsep/祖母宜興縣太君王氏,祖子開/wsep//vno//no_noc//wsep/祖母/ns//no_noc/王氏,NaN,宜興,中散大夫#縣太君,贈
4992,13538,5140666,王安石,NaN,母,朱,公先喪其母韓國夫人朱氏/wsep/事繼母魯國太夫人張氏/wsep/以孝聞,公先喪其母/ns/夫人朱氏/wsep/事繼母/ns/太夫人張氏/wsep/以孝聞,NaN,韓國#魯國,NaN,NaN
4246,36127,5657787,陳良祐,楊椿,妣,侯,妣侯氏/wsep/武陵郡夫人/wsep/宋氏/wsep/同安郡夫人,妣侯氏/wsep//ns/夫人/wsep/宋氏/wsep//ns/夫人,NaN,武陵郡#同安郡,NaN,NaN
5128,10406,5467707,鄭剛中,符授,母,瞿,丁母南康郡夫人瞿氏憂/wsep/服除/wsep/調卲州卲陽縣主簿/wsep/就移筠州上高縣令,丁母/ns/夫人瞿氏憂/wsep/服除/wsep/調卲州卲陽/no_noc//wsep/就/...,NaN,南康郡#筠州#上高,縣主簿#縣令,移

In [17]:
df_kin_extracted[df_kin_extracted['name']!=''].drop('sent_comp_index', axis=1).sort_values(by='content_id').to_excel('../output/df_qsw_kin_extracted_female.xlsx', encoding='utf8')

### Son/Daughter kinship extraction.

In [167]:
re_rule_list=[r'(子|孫|曾孫|男|女|婿)曰([^/]+?)\/',
              r'(子男)(.{0,3}?)人(\/.+)',
              r'[^女]*(曾孫|孫)([^女]{0,3}?)人(\/.+)',
              r'[^女]*(孫子|子)([^男女]{0,3}?)人(\/.+)',
             ]

In [168]:
kin_list=[]
df_kin_extracted=pd.DataFrame()
list_temp=[]
for re_rule in re_rule_list:
    for index in tqdm(df_sent_comp.index):
        string=df_sent_comp.loc[index, 'sent_comp']
        content_id=df_sent_comp.loc[index, 'content_id']
        author=df_sent_comp.loc[index, 'author']
        subj=df_sent_comp.loc[index, 'subject']
        kin_list_temp=re.findall(re_rule, string)
        if kin_list_temp!=[]:
            for kin_nm in kin_list_temp:
                if len(kin_nm)==2:
                    kin_nm=(kin_nm[0], '', kin_nm[1])
                df_kin_extracted=pd.concat([pd.DataFrame([list(kin_nm)+[re_rule, string, content_id, author, subj]]), 
                                            df_kin_extracted], ignore_index=True)
                list_temp.append(kin_nm)

100%|██████████| 57733/57733 [00:07<00:00, 7847.08it/s]
100%|██████████| 57733/57733 [00:08<00:00, 7096.03it/s]
100%|██████████| 57733/57733 [00:15<00:00, 3672.16it/s]
100%|██████████| 57733/57733 [00:13<00:00, 4331.55it/s]

In [169]:
df_kin_extracted=df_kin_extracted.rename(columns={0:'kin', 1:'number', 2:'name_string', 
                                                  3:'re_rule', 4:'sent_comp', 5:'content_id',
                                                  6:'author', 7:'subj'})

In [170]:
del_dict=['長','次','幼','曰','貢','等','第','及第','中第','新','知','舊','監','倉','起','終','故','前','後','左','右','州','軍',
          '路','郡','縣','尉','某官','官','税務','支鹽','俱業','今以','皆','並','并','餘','俱','早夭','夭','卒','幼','尚幼','未名',
          '前卒','先卒','蚤卒','俱有','未仕','未銓','左銓','致仕','出身',]

In [171]:
def clean_name_string(name_string):
    global del_dict
    name_string_list=[s for s in re.sub(r'[a-z_]', '', name_string).split('/') if s!='']
    name_string_list_refined=[]
    for name_string in name_string_list:
        for del_string in del_dict:
            name_string=name_string.replace(del_string, '')
        if name_string!='' and len(name_string)<=2:
            name_string_list_refined.append(name_string)
    return name_string_list_refined

In [172]:
df_kin_extracted['name_string']=[clean_name_string(s) for s in df_kin_extracted['name_string']]

In [174]:
df_kin_extracted.to_excel('../output/df_kin_extracted_son_dau_etc.xlsx', encoding='utf8')